server:
  port: 8080
  
spring:
  config:
    import: configserver:http://localhost:9296    
  application:
    name: PRODUCT-SERVICE      
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update   
     
          

    
#eureka:
  #instance:
   # prefer-ip-address: true
  #client:
    #fetch-registry: true
    #register-with-eureka: true
    #service-url:
      #defaultZone: http://localhost:8761/eureka